#%RAML 1.0 DocumentationItem
title: How to write Examples
content: |
  # Rules for Writing Examples

  1. Test.

  # When to use Examples
    1. Test

  # A Good Example...Example

    See `good-example-api.raml` for a sample
