#%RAML 1.0 NamedExample
value:
  - id: 1
    name: Alice Dupont
    email: alice.dupont@example.com
    companyDateEntry: 2003-05-14
    postal_code: "075001"
  - id: 2
    name: Bob Martin
    email: bob.martin@example.com
    companyDateEntry: 2004-05-04
    postal_code: "169002"
  - id: 3
    name: Charlie Durand
    email: charlie.durand@example.com
    companyDateEntry: 2003-08-11
    postal_code: "013003"
